const information = {
    "MX-AGU" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-BCN" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-BCS" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-CAM" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-CHP" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-CHH" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-COA" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-COL" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-CDMX" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-DUR" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-GUA" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-GRO" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-HID" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-JAL" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-MEX" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-MIC" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-MOR" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-NAY" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-NEL" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-OAX" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-PUE" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-QUE" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-ROO" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-SLP" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-SIN" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-SON" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-TAB" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-TAM" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-TLA" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-VER" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-YUC" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    },
    "MX-ZAC" : {
        name: "Colima",
        dependencias: [
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro:""},
            {denunciaLugar: "https://www.colima.gob.mx/",
            pagina: "https://www.colima.gob.mx/",
            telefono: "55-33-00-00",
            whatsapp: "55-33-00-00",
            email: "",
            facebook: "https://www.facebook.com/colimagob/",
            twitter: "https://twitter.com/colimagob",
            otro: ""}
        ]
    }
};

export default information;